twig:
    file_name_pattern: '*.twig'
    paths:
        # '%kernel.project_dir%/assets/images': images
        '%kernel.project_dir%/assets/styles': styles
        # '%kernel.project_dir%/assets/fonts': fonts

when@test:
    twig:
        strict_variables: true
